### ISSUE TITLE
CHARMM forcefields (19 and 22) can't be used

### ISSUE THREAD

**Issue by gusennan** [donaldlab/OSPREY3#102]
It appears that the parameter files are either misspelled in the code or missing from the config directory.  I've attached a sample script that causes the following error on CHARMM19:

```
OSPREY 3.1-beta1-b138
Using up to 1024 MiB heap memory: 128 MiB for garbage, 896 MiB for storage
read PDB file from file: 2RL0.min.reduce.pdb
Traceback (most recent call last):
  File "kstar2.py", line 12, in <module>
    templateLib = osprey.TemplateLibrary(forcefield=osprey.Forcefield.CHARMM19)
  File "/home/home2/nguerin/.local/lib/python2.7/site-packages/osprey/__init__.py", line 362, in TemplateLibrary
    return builder.build()
jpype._jexception.ErrorPyRaisable: java.lang.Error: can't read forcefield params

java.lang.Error: can't read forcefield params
        at edu.duke.cs.osprey.energy.forcefield.ForcefieldParams.init(ForcefieldParams.java:253)
        at edu.duke.cs.osprey.energy.forcefield.ForcefieldParams.<init>(ForcefieldParams.java:243)
        at edu.duke.cs.osprey.restypes.ResidueTemplateLibrary.<init>(ResidueTemplateLibrary.java:243)
        at edu.duke.cs.osprey.restypes.ResidueTemplateLibrary$Builder.build(ResidueTemplateLibrary.java:218)
Caused by: java.lang.RuntimeException: can't find resource on classpath: /config/parmcharm19.dat
        at edu.duke.cs.osprey.tools.FileTools$ResourcePathRoot.open(FileTools.java:247)
        at edu.duke.cs.osprey.tools.FileTools$PathRoot.read(FileTools.java:61)
        at edu.duke.cs.osprey.tools.FileTools.readResource(FileTools.java:346)
        at edu.duke.cs.osprey.energy.forcefield.ForcefieldParams.readParm96(ForcefieldParams.java:291)
        at edu.duke.cs.osprey.energy.forcefield.ForcefieldParams.init(ForcefieldParams.java:250)
        ... 3 more

```

a similar error occurs with CHARMM22.

[error-script.zip](https://github.com/donaldlab/OSPREY3/files/3708413/error-script.zip)

**Comment by gusennan** [comment]
Closing due to inactivity
