### ISSUE TITLE
LUTE Example not working

### ISSUE THREAD

**Issue by hnisonoff** [donaldlab/OSPREY3#109]
Hello! I have been using OSPREY 3.2 and haven't run into issues until I tried out LUTE. I cannot even get the example to run. Have you noticed this on your end? Thanks!

```
> python findGMEC.LUTE.design.py
OSPREY 3.2-beta1-dev, Python 3.7.6, Java 11.0.6, Darwin-19.4.0-x86_64-i386-64bit
Using up to 1024 MiB heap memory: 128 MiB for garbage, 896 MiB for storage
read PDB file from file: 1CC8.ss.pdb
read pruning matrix from file: /Users/hunternisonoff/Box Sync/Berkeley/BioML/Covid19/moldyn/osprey_install/osprey-osx-python3-3.2-beta1/examples/python.GMEC/LUTE.pmat.dat
LUTE model read from /Users/hunternisonoff/Box Sync/Berkeley/BioML/Covid19/moldyn/osprey_install/osprey-osx-python3-3.2-beta1/examples/python.GMEC/LUTE.dat
Traceback (most recent call last):
  File "LUTEConfEnergyCalculator.java", line 49, in edu.duke.cs.osprey.lute.LUTEConfEnergyCalculator.<init>
  File "ConfEnergyCalculator.java", line 129, in edu.duke.cs.osprey.energy.ConfEnergyCalculator.<init>
  File "ConfEnergyCalculator.java", line 142, in edu.duke.cs.osprey.energy.ConfEnergyCalculator.<init>
Exception: Java Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "findGMEC.LUTE.design.py", line 19, in <module>
    gmecFinder = osprey.LUTE_GMECFinder(confSpace, model, pmat, printIntermediateConfs=True)
  File "/Users/hunternisonoff/.local/lib/python3.7/site-packages/osprey/__init__.py", line 1287, in LUTE_GMECFinder
    builder = _get_builder(c.lute.LUTEGMECFinder)(pmat, LUTE_ConfEnergyCalculator(confSpace, model))
  File "/Users/hunternisonoff/.local/lib/python3.7/site-packages/osprey/__init__.py", line 1245, in LUTE_ConfEnergyCalculator
    return c.lute.LUTEConfEnergyCalculator(confSpace, model)
osprey.NullPointerException: java.lang.NullPointerException

java.lang.NullPointerException
	at edu.duke.cs.osprey.energy.ConfEnergyCalculator.<init>(ConfEnergyCalculator.java:142)
	at edu.duke.cs.osprey.energy.ConfEnergyCalculator.<init>(ConfEnergyCalculator.java:129)
	at edu.duke.cs.osprey.lute.LUTEConfEnergyCalculator.<init>(LUTEConfEnergyCalculator.java:49)

```

**Comment by cuchaz** [comment]
Hi Hunter!
I think there might have been some regressions with LUTE in the v3.2 release. I fixed a whole bunch of stuff recently in newer commits though. Want to try compiling from source on the latest `master` commit and see if you still have the problem?

**Comment by cuchaz** [comment]
Oh, we have pre-built binaries too. I keep forgetting about those. If you want a pre-build of the latest `master`, let me know. I'll send it to you. You want the Python 3 verison, right?

**Comment by hnisonoff** [comment]
Yes, python3 please! Thank you!

**Comment by gusennan** [comment]
Hey @hnisonoff did that fix this issue for you?

**Comment by gusennan** [comment]
I think I fixed this. It ran when I tested it on a mac. There's a train script that has to be run first (it's mislabeled in the example), but when I run the train and then design scripts, they run to completion. 

About to create a new release here on GitHub with the version that works. Feel free to reopen if it's still an issue!
