### ISSUE TITLE
Error in OSPREY3/examples/python.GMEC/findGMEC.DEEPer.py

### ISSUE THREAD

**Issue by Clint-Holt** [donaldlab/OSPREY3#114]
Issue in making the DEEPerStrandFlex conformational space. Running the example as is causes the error:
"File "findGMEC.DEEPer.py", line 19, in <module>
    pdb_file='1CC8.ss.pdb')
  File "/home/holtcm/.local/lib/python2.7/site-packages/osprey/__init__.py", line 900, in DEEPerStrandFlex
    bbflex = c.confspace.DEEPerStrandFlex(strand,deeper_settings)
  File "/home/holtcm/.local/lib/python2.7/site-packages/jpype/_jclass.py", line 87, in _javaInit
    self.__javaobject__ = self.__class__.__javaclass__.newClassInstance(*args)
jpype._jexception.IllegalArgumentExceptionPyRaisable: java.lang.IllegalArgumentException: can't resolve path: 1CC8.ss.pdb
path is not absolute and no relative root was set

java.lang.IllegalArgumentException: can't resolve path: 1CC8.ss.pdb
path is not absolute and no relative root was set
	at edu.duke.cs.osprey.tools.FileTools$ResourcePathRoot.resolve(FileTools.java:224)
	at edu.duke.cs.osprey.tools.FileTools$ResourcePathRoot.open(FileTools.java:242)
	at edu.duke.cs.osprey.tools.FileTools$PathRoot.read(FileTools.java:61)
	at edu.duke.cs.osprey.tools.FileTools.readResource(FileTools.java:346)
	at edu.duke.cs.osprey.dof.deeper.PerturbationSelector.<init>(PerturbationSelector.java:98)
	at edu.duke.cs.osprey.dof.deeper.DEEPerSettings.loadPertFile(DEEPerSettings.java:118)
	at edu.duke.cs.osprey.confspace.DEEPerStrandFlex.<init>(DEEPerStrandFlex.java:63)"

Whereas specifying the exact path for the pdb file results in the following error:
"Traceback (most recent call last):
  File "findGMEC.DEEPer.py", line 19, in <module>
    pdb_file=pdb)
  File "/home/holtcm/.local/lib/python2.7/site-packages/osprey/__init__.py", line 900, in DEEPerStrandFlex
    bbflex = c.confspace.DEEPerStrandFlex(strand,deeper_settings)
  File "/home/holtcm/.local/lib/python2.7/site-packages/jpype/_jclass.py", line 87, in _javaInit
    self.__javaobject__ = self.__class__.__javaclass__.newClassInstance(*args)
jpype._jexception.RuntimeExceptionPyRaisable: java.lang.RuntimeException: can't find resource on classpath: /gpfs52/home/holtcm/humira/gmec-jobs/practice/DEEPer/1CC8.ss.pdb

java.lang.RuntimeException: can't find resource on classpath: /gpfs52/home/holtcm/humira/gmec-jobs/practice/DEEPer/1CC8.ss.pdb
	at edu.duke.cs.osprey.tools.FileTools$ResourcePathRoot.open(FileTools.java:247)
	at edu.duke.cs.osprey.tools.FileTools$PathRoot.read(FileTools.java:61)
	at edu.duke.cs.osprey.tools.FileTools.readResource(FileTools.java:346)
	at edu.duke.cs.osprey.dof.deeper.PerturbationSelector.<init>(PerturbationSelector.java:98)
	at edu.duke.cs.osprey.dof.deeper.DEEPerSettings.loadPertFile(DEEPerSettings.java:118)
	at edu.duke.cs.osprey.confspace.DEEPerStrandFlex.<init>(DEEPerStrandFlex.java:63)"

The issue occurred on both Linux CENTOS 7 and MacOS Catalina 10.15 operating systems

**Comment by Clint-Holt** [comment]
For reference I got this bug in both the 3.1 and 3.2 releases, but I just downloaded the 3.0 release and the script worked perfectly there! I'm fine reverting to the earlier release, but if anyone has good workarounds for doing continuous backbone flexibility on GMEC runs for the 3.1 or 3.2 releases I'd love to hear them.

**Comment by gusennan** [comment]
Hi Clint,

Are you using the examples that are packaged with the distribution you downloaded, or are you downloading the examples from the website and trying to run them? Only the former works.

Please let us know,
Nate

**Comment by Clint-Holt** [comment]
Hi Nate I am using the examples packaged with the distribution. Do they work on your machine?

**Comment by gusennan** [comment]
Hi Clint,

Thanks for reporting the issue.  I fixed the bug.  Builds can be downloaded from 

https://drive.google.com/drive/u/0/folders/1v_mthJnzOje2gLj9PV1gsg7uCoNlmmPV

Any with today's date or later (2020-05-05) will have the fix.

**Comment by Clint-Holt** [comment]
Thanks so much!
