### ISSUE TITLE
Error in OSPREY3/examples/python.GMEC/findGMEC.cats.py

### ISSUE THREAD

**Issue by Clint-Holt** [donaldlab/OSPREY3#115]
Running the following code results in this error:
>>>python findGMEC.cats.py
Traceback (most recent call last):
  File "/Applications/osprey-osx-python2-3.2-beta1/examples/python.GMEC/findGMEC.cats.py", line 36, in <module>
    gmec = dgf.calcGMEC()
jpype._jexception.ErrorPyRaisable: java.lang.Error: can't write object

java.lang.Error: can't write object
	at edu.duke.cs.osprey.tools.ObjectIO.writeObject(ObjectIO.java:180)
	at edu.duke.cs.osprey.gmec.PrecomputedMatrices.loadMatrix(PrecomputedMatrices.java:256)
	at edu.duke.cs.osprey.gmec.PrecomputedMatrices.loadEPICMatrix(PrecomputedMatrices.java:236)
	at edu.duke.cs.osprey.gmec.PrecomputedMatrices.precompute(PrecomputedMatrices.java:165)
	at edu.duke.cs.osprey.gmec.PrecomputedMatrices.<init>(PrecomputedMatrices.java:110)
	at edu.duke.cs.osprey.gmec.DEEGMECFinder.calcGMEC(DEEGMECFinder.java:142)
	at edu.duke.cs.osprey.gmec.DEEGMECFinder.calcGMEC(DEEGMECFinder.java:120)
Caused by: java.io.NotSerializableException: edu.duke.cs.osprey.dof.MutAlignmentCache
	at java.base/java.io.ObjectOutputStream.writeObject0(Unknown Source)
	at java.base/java.io.ObjectOutputStream.defaultWriteFields(Unknown Source)
	at java.base/java.io.ObjectOutputStream.writeSerialData(Unknown Source)
	at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(Unknown Source)
	at java.base/java.io.ObjectOutputStream.writeObject0(Unknown Source)
	at java.base/java.io.ObjectOutputStream.defaultWriteFields(Unknown Source)
	at java.base/java.io.ObjectOutputStream.writeSerialData(Unknown Source)
	at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(Unknown Source)
	at java.base/java.io.ObjectOutputStream.writeObject0(Unknown Source)
	at java.base/java.io.ObjectOutputStream.writeObject(Unknown Source)
	at edu.duke.cs.osprey.tools.ObjectIO.writeObject(ObjectIO.java:172)
	... 6 more

The same error occurs in release 3.1 and occurs in both Linux CENTOS 7 and MacOS 10.15 operating systems

**Comment by Clint-Holt** [comment]
Although findGMEC.cats.py is not included as an example script for OSPREY version 3.0 this script does work with version 3.0 of OSPREY

**Comment by gusennan** [comment]
Hi Clint,

Thanks for this issue report! Could you please attach the exact scripts that you ran and tell me if you compiled Osprey yourself or if you downloaded it from here?

Thanks,
Nate

**Comment by Clint-Holt** [comment]
I tried the default example python scripts that came with OSPREY 3.2 and 3.1 downloaded separately on Linux, Mac, and Windows computers. Here is one version from OSPREY 3.2 on Mac that didn't work. 

[findGMEC.cats.txt](https://github.com/donaldlab/OSPREY3/files/4584003/findGMEC.cats.txt)
It wouldn't let me upload a python file so all I did was change the extension to '.txt'. All you need to do is change it back to '.py'

I downloaded OSPREY from https://github.com/donaldlab/OSPREY3/releases . Do you recommend I compile it myself instead?

**Comment by gusennan** [comment]
the fix for issue 114, as well as the associated PR, fixes this issue. You can get the latest builds from the google drive folder referenced in 114.

In general, we recommend using the K* set of algorithms rather than the GMEC set of algorithms, because K*, because molecules exist as thermodynamic ensembles and not as a single low-energy structure.  You get a provable approximation to the ensemble using K*, whereas with the GMEC algorithms you only get a single structure.

**Comment by Clint-Holt** [comment]
Hi maybe you can help me apply K* in my particular instance then. I am
designing point mutants on an antibody that eliminate binding to its
antigen except I do not have a co-crystal structure of the complex, I only
have the structure of the antibody and a decent knowledge of how it binds
the antigen. Since I don't have the complex structure I am using a single
strand to represent the antibody in OSPREY and then am testing alternate
amino acid types at a single residue position to get a point mutant with
very different properties, but with favorable overall energetics.
What I am afraid of is that if I choose a split in my single strand
representing the antibody into two strands, a "protein" and a "ligand"
strand, that the top results returned to me by OSPREY will be the mutation
that optimizes the interface between these two strands whereas what I
really want is the mutation that gives me the lowest overall energy for my
antibody. I personally have really liked your K* algorithms in designing
interface positions and I have wished that I could get some
boltzmann-weighted average for my GMEC designs so if you have thoughts for
how to apply K* to redesigning non-interface residues without biasing the
results they would be very helpful.

**Comment by gusennan** [comment]
Your understanding is correct. K* provably approximates binding.  But the way that it approximates binding is by computing epsilon-approximate partition functions for three states: The bound protein-ligand complex, the apo protein, and apo ligand. These are then made into a ratio ([complex])/([protein][ligand]). 

The partition function is a thermodynamic ensemble.  While you can't, say, make the entire protein flexible, you will get an idea of how certain mutations affect stability by computing the single partition function of the antibody and varying mutations.

**Comment by Clint-Holt** [comment]
Thank you! Yes, that makes sense. Also sorry to keep bothering you, but is
it currently possible to use EPIC with K* or BBK*?

**Comment by gusennan** [comment]
I don't believe so, or rather, I haven't heard of someone doing so. It might be possible.
