### ISSUE TITLE
May 6th build causes error in SimplerEnergyMatrixCalculator

### ISSUE THREAD

**Issue by Clint-Holt** [donaldlab/OSPREY3#120]
The examples/python.KStar/bkkstar.py script no longer works after the latest bug fixes. Here's the error message.

OSPREY 3.2-beta1-b194, Python 2.7.18, Java 11.0.2, Linux-3.10.0-957.1.3.el7.x86_64-x86_64-with-centos-7.6.1810-Core
Using up to 1024 MiB heap memory: 128 MiB for garbage, 896 MiB for storage
read PDB file from file: 2RL0.min.reduce.pdb
Calculating reference energies for 0 residue confs...
Traceback (most recent call last):
  File "bbkstar.py", line 69, in <module>
    ematMinimized = osprey.EnergyMatrix(info.confEcalcMinimized, cacheFile='emat.%s.dat' % info.id)
  File "/gpfs52/home/holtcm/conda/osprey32/lib/python2.7/site-packages/osprey/__init__.py", line 684, in EnergyMatrix
    return builder.build().calcEnergyMatrix()
jpype._jexception.IndexOutOfBoundsExceptionPyRaisable: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Unknown Source)
	at java.base/java.util.Objects.checkIndex(Unknown Source)
	at java.base/java.util.ArrayList.get(Unknown Source)
	at edu.duke.cs.osprey.ematrix.SimpleReferenceEnergies.getOffset(SimpleReferenceEnergies.java:95)
	at edu.duke.cs.osprey.energy.EnergyPartition$1.makeSingle(EnergyPartition.java:51)
	at edu.duke.cs.osprey.energy.ConfEnergyCalculator.makeSingleInters(ConfEnergyCalculator.java:212)
	at edu.duke.cs.osprey.ematrix.SimplerEnergyMatrixCalculator.reallyCalcEnergyMatrix(SimplerEnergyMatrixCalculator.java:175)
	at edu.duke.cs.osprey.ematrix.SimplerEnergyMatrixCalculator.lambda$calcEnergyMatrix$1(SimplerEnergyMatrixCalculator.java:157)
	at edu.duke.cs.osprey.tools.ObjectIO.readOrMake(ObjectIO.java:243)
	at edu.duke.cs.osprey.ematrix.SimplerEnergyMatrixCalculator.calcEnergyMatrix(SimplerEnergyMatrixCalculator.java:152)

Script:  [bbkstar.txt](https://github.com/donaldlab/OSPREY3/files/4589081/bbkstar.txt)

**Comment by gusennan** [comment]
You're quick, thank you.

**Comment by gusennan** [comment]
Fixed by #0fd9b21a378e441de45448826ab72797e658a572

**Comment by gusennan** [comment]
Thanks for the report. Please try out the latest build and let me know if you still run into this issue.
