### ISSUE TITLE
ConfDB appears to be using unsafe code

### ISSUE THREAD

**Issue by gusennan** [donaldlab/OSPREY3#125]
Running the attached script on 3.2.101 produces the following exception:

```
➜  osprey-files cat florian-no-confdb.err 
Traceback (most recent call last):
  File "BBKStar.java", line 590, in edu.duke.cs.osprey.kstar.BBKStar.run
  File "BBKStar.java", line 179, in edu.duke.cs.osprey.kstar.BBKStar$ConfSpaceInfo.openConfDB
  File "ConfDB.java", line 746, in edu.duke.cs.osprey.confspace.ConfDB.<init>
  File "DBMaker.kt", line 477, in org.mapdb.DBMaker$Maker.make
  File "DB.kt", line 40, in org.mapdb.DB.<init>
  File "DB.kt", line 269, in org.mapdb.DB.<init>
  File "StoreWAL.kt", line 595, in org.mapdb.StoreWAL.commit
  File "WriteAheadLog.java", line 911, in org.mapdb.WriteAheadLog.walPutByteArray
  File "WriteAheadLog.java", line 1009, in org.mapdb.WriteAheadLog.ensureFileReady
  File "WriteAheadLog.java", line 135, in org.mapdb.WriteAheadLog.startNextFile
  File "ByteBufferVol.java", line 53, in org.mapdb.volume.ByteBufferVol.putLong
  File "java.nio.DirectByteBuffer.java", line -1, in java.nio.DirectByteBuffer.putLong
  File "java.nio.DirectByteBuffer.java", line -1, in java.nio.DirectByteBuffer.putLong
  File "jdk.internal.misc.Unsafe.java", line -1, in jdk.internal.misc.Unsafe.putLongUnaligned
  File "jdk.internal.misc.Unsafe.java", line -1, in jdk.internal.misc.Unsafe.putLongUnaligned
  File "jdk.internal.misc.Unsafe.java", line -2, in jdk.internal.misc.Unsafe.putLong
Exception: Java Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "bbkstar.py", line 153, in <module>
    scoredSequences = bbkstar.run(minimizingEcalc.tasks)
__main__.InternalError: java.lang.InternalError: a fault occurred in a recent unsafe memory access operation in compiled Java code



The job can be submitted to slurm using 

`sbatch run-test.sh`

```

![osprey-files.zip](https://github.com/donaldlab/OSPREY3/files/4689207/osprey-files.zip)

**Comment by cuchaz** [comment]
The python script in the zip file doesn't seem to use ConfDB at all, yet the crash is happening inside the ConfDB code. Are you sure that script produces this crash?

**Comment by gusennan** [comment]
Yes, I'm sure, I produced those errors this morning.  That's really weird.

Did you run it with the slurm submission script? I ran it on grisman-39 and it produced that error. 

When you ran it, did it produce any error or did it run to completion?

**Comment by cuchaz** [comment]
I actually got a different unrelated error that happens after the error reported here would have happened, probably because I ran the script against whatever code I had in a local branch, rather than the up-to-date master branch.

Actually, I thought the ConfDB system was off by default, and I got confused that the python script wasn't turning it on. Then I remembered that the ConfDB system is on by default now, so there doesn't need to be any references to it in the python script.

So now my best guess for the cause of the error (which I still can't reproduce) is trying to re-use databases between different designs, which is undefined behavior. I have no idea what kind of havoc that would cause. Possibly it could cause the error you reported?

Ie, try deleting your confdb files in the filesystem and see if the error goes away or not.

**Comment by gusennan** [comment]
Ok. Let me poke at it some more. I'm running using the release from here (installed it using the install script as a user would) and not actually the source from master, and I wonder if that might have something to do with it.

**Comment by cuchaz** [comment]
Ok. Btw, reusing confdb files between designs could be as simple as adding or removing flexible/mutable residues to/from your python script and running it again. Technically, that's a different design from the code's point of view, and if the confdb files are still in the filesystem, they'll get reused, which is probably not what the user wants.

**Comment by gusennan** [comment]
Closing due to inactivity
