### ISSUE TITLE
Race issue in ThreadPoolTaskExecutor?

### ISSUE THREAD

**Issue by gusennan** [donaldlab/OSPREY3#127]
From time to time when I run a design I encounter the following bug.  I've seen it in maybe 10% of my runs, and seems to occur when more CPUs are allocated (e.g. giving 48 CPUs to parallelism vs 20 CPUs _seems_ to increase the proportion of occurences), and re-running the same design with the same parameters tends to work the second time.  

```
WARNING: couldn't find solvation parameters for atom N2 @ B253, using default values
WARNING: couldn't find solvation parameters for atom N10 @ B253, using default values
edu.duke.cs.osprey.parallelism.TaskExecutor$TaskException: A task failed, no new tasks can be submitted
        at edu.duke.cs.osprey.parallelism.ConcurrentTaskExecutor.recordException(ConcurrentTaskExecutor.java:106)
        at edu.duke.cs.osprey.parallelism.ConcurrentTaskExecutor.taskFailure(ConcurrentTaskExecutor.java:87)
        at edu.duke.cs.osprey.parallelism.ThreadPoolTaskExecutor.lambda$submit$1(ThreadPoolTaskExecutor.java:109)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IndexOutOfBoundsException
        at java.base/java.nio.Buffer.checkIndex(Unknown Source)
        at java.base/java.nio.DirectByteBuffer.get(Unknown Source)
        at org.mapdb.DataInput2$ByteBuffer.readUnsignedByte(DataInput2.java:313)
        at edu.duke.cs.osprey.tools.IntEncoding$1.read(IntEncoding.java:53)
        at edu.duke.cs.osprey.confspace.ConfDB$AssignmentsSerializer.deserialize(ConfDB.java:213)
        at edu.duke.cs.osprey.confspace.ConfDB$AssignmentsSerializer.deserialize(ConfDB.java:188)
        at org.mapdb.serializer.GroupSerializerObjectArray.valueArrayDeserialize(GroupSerializerObjectArray.java:26)
        at org.mapdb.serializer.GroupSerializerObjectArray.valueArrayDeserialize(GroupSerializerObjectArray.java:14)
        at org.mapdb.BTreeMapJava$NodeSerializer.deserialize(BTreeMapJava.java:183)
        at org.mapdb.BTreeMapJava$NodeSerializer.deserialize(BTreeMapJava.java:136)
        at org.mapdb.StoreDirectAbstract.deserialize(StoreDirectAbstract.kt:229)
        at org.mapdb.StoreWAL.get(StoreWAL.kt:527)
        at org.mapdb.BTreeMap.getNode(BTreeMap.kt:800)
        at org.mapdb.BTreeMap.getNonBinary(BTreeMap.kt:276)
        at org.mapdb.BTreeMap.get(BTreeMap.kt:235)
        at edu.duke.cs.osprey.confspace.ConfDB$ConfTable.getEnergied(ConfDB.java:425)
        at edu.duke.cs.osprey.energy.ConfEnergyCalculator.calcEnergy(ConfEnergyCalculator.java:481)
        at edu.duke.cs.osprey.energy.ConfEnergyCalculator.calcEnergy(ConfEnergyCalculator.java:399)
        at edu.duke.cs.osprey.kstar.pfunc.GradientDescentPfunc$EnergyTask.run(GradientDescentPfunc.java:551)
        at edu.duke.cs.osprey.kstar.pfunc.GradientDescentPfunc$EnergyTask.run(GradientDescentPfunc.java:506)
        at edu.duke.cs.osprey.parallelism.TaskExecutor.runTask(TaskExecutor.java:166)
        at edu.duke.cs.osprey.parallelism.ThreadPoolTaskExecutor.lambda$submit$1(ThreadPoolTaskExecutor.java:101)
        ... 3 more
```

Attached are the kstar script and additional files that were used to generate this error on slurm.

[KE70-r2-7-12f-rs.zip](https://github.com/donaldlab/OSPREY3/files/4708060/KE70-r2-7-12f-rs.zip)

**Comment by cuchaz** [comment]
The thread pool task executor has been in use for a long time now and we haven't seen any evidence of races. I'd be surprised if the problem was there. The MapDB subsystem is a more likely source of race conditions though. MapDB is supposed to be thread-safe, but it's possible it has some bugs. We could try updating to the newest version of MapDB. Or just synchronize all access to MapDB so we don't have to depend on its thread safety.

**Comment by gusennan** [comment]
That sounds reasonable. Is it possible that mapdb is thread-safe, i.e. multiple threads can access it at the same time, but does not guarantee ordering?

**Comment by cuchaz** [comment]
I'm not really sure what MapDB's specific thread safety guarantees are. Here's all the info I can find:
```
It is thread safe, and supports parallel writes by using multiple segments, each with separate ReadWriteLock. ConcurrentHashMap in JDK 7 works in a similar way. The number of segments (also called concurrency factor) is configurable.
```
https://jankotek.gitbooks.io/mapdb/htreemap/

Although, that's for the `HTreeMap` and I think in this case we're using the `BTreeMap`. There's no mention of thread safety on [the page for the `BTreeMap`](https://jankotek.gitbooks.io/mapdb/content/btreemap/), so maybe it's really not thread-safe?

**Comment by gusennan** [comment]
Closing due to inactivity.
