### ISSUE TITLE
Issues with confdb

### ISSUE THREAD

**Issue by gusennan** [donaldlab/OSPREY3#143]
These seem to be coming from perhaps a bug either in our usage of or within mapdb itself. These were two designs ran in their own temporary directories to ensure independent creation and usage of the DB. 

How much faster is using the conf cache compared to not using it?

```
edu.duke.cs.osprey.parallelism.TaskExecutor$TaskException: A task failed, no new tasks can be submitted
        at edu.duke.cs.osprey.parallelism.ConcurrentTaskExecutor.recordException(ConcurrentTaskExecutor.java:106)
        at edu.duke.cs.osprey.parallelism.ConcurrentTaskExecutor.taskFailure(ConcurrentTaskExecutor.java:87)
        at edu.duke.cs.osprey.parallelism.ThreadPoolTaskExecutor.lambda$submit$1(ThreadPoolTaskExecutor.java:109)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IndexOutOfBoundsException: Index: 891770185 Size: 4
        at org.eclipse.collections.impl.list.mutable.primitive.LongArrayList.newIndexOutOfBoundsException(LongArrayList.java:135)
        at org.eclipse.collections.impl.list.mutable.primitive.LongArrayList.get(LongArrayList.java:130)
        at org.eclipse.collections.impl.list.mutable.primitive.SynchronizedLongList.get(SynchronizedLongList.java:71)
        at org.mapdb.StoreDirectAbstract.recidToOffset(StoreDirectAbstract.kt:52)
        at org.mapdb.StoreWAL.getIndexVal(StoreWAL.kt:164)
        at org.mapdb.StoreWAL.get(StoreWAL.kt:499)
        at org.mapdb.BTreeMap.getNode(BTreeMap.kt:800)
        at org.mapdb.BTreeMap.getNonBinary(BTreeMap.kt:276)
        at org.mapdb.BTreeMap.get(BTreeMap.kt:235)
        at edu.duke.cs.osprey.confspace.ConfDB$ConfTable.getEnergied(ConfDB.java:425)
        at edu.duke.cs.osprey.energy.ConfEnergyCalculator.calcEnergy(ConfEnergyCalculator.java:481)
        at edu.duke.cs.osprey.energy.ConfEnergyCalculator.calcEnergy(ConfEnergyCalculator.java:399)
        at edu.duke.cs.osprey.kstar.pfunc.GradientDescentPfunc$EnergyTask.run(GradientDescentPfunc.java:551)
        at edu.duke.cs.osprey.kstar.pfunc.GradientDescentPfunc$EnergyTask.run(GradientDescentPfunc.java:506)
        at edu.duke.cs.osprey.parallelism.TaskExecutor.runTask(TaskExecutor.java:166)
        at edu.duke.cs.osprey.parallelism.ThreadPoolTaskExecutor.lambda$submit$1(ThreadPoolTaskExecutor.java:101)
        ... 3 more
```

```
edu.duke.cs.osprey.parallelism.TaskExecutor$TaskException: A task failed, no new tasks can be submitted
        at edu.duke.cs.osprey.parallelism.ConcurrentTaskExecutor.recordException(ConcurrentTaskExecutor.java:106)
        at edu.duke.cs.osprey.parallelism.ConcurrentTaskExecutor.taskFailure(ConcurrentTaskExecutor.java:87)
        at edu.duke.cs.osprey.parallelism.ThreadPoolTaskExecutor.lambda$submit$1(ThreadPoolTaskExecutor.java:109)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ArrayIndexOutOfBoundsException: arraycopy: source index -1 out of bounds for object array[2]
        at java.base/java.lang.System.arraycopy(Native Method)
        at org.mapdb.DataIO.arrayPut(DataIO.java:531)
        at org.mapdb.serializer.GroupSerializerObjectArray.valueArrayPut(GroupSerializerObjectArray.java:44)
        at org.mapdb.serializer.GroupSerializerObjectArray.valueArrayPut(GroupSerializerObjectArray.java:14)
        at org.mapdb.BTreeMap.copyAddKeyLeaf(BTreeMap.kt:645)
        at org.mapdb.BTreeMap.put2(BTreeMap.kt:403)
        at org.mapdb.BTreeMap.put(BTreeMap.kt:292)
        at edu.duke.cs.osprey.confspace.ConfDB$ConfTable.setBounds(ConfDB.java:363)
        at edu.duke.cs.osprey.confspace.ConfDB$ConfTable.setBounds(ConfDB.java:343)
        at edu.duke.cs.osprey.energy.ConfEnergyCalculator.calcEnergy(ConfEnergyCalculator.java:493)
        at edu.duke.cs.osprey.energy.ConfEnergyCalculator.calcEnergy(ConfEnergyCalculator.java:399)
        at edu.duke.cs.osprey.kstar.pfunc.GradientDescentPfunc$EnergyTask.run(GradientDescentPfunc.java:551)
        at edu.duke.cs.osprey.kstar.pfunc.GradientDescentPfunc$EnergyTask.run(GradientDescentPfunc.java:506)
        at edu.duke.cs.osprey.parallelism.TaskExecutor.runTask(TaskExecutor.java:166)
        at edu.duke.cs.osprey.parallelism.ThreadPoolTaskExecutor.lambda$submit$1(ThreadPoolTaskExecutor.java:101)
        ... 3 more

```

**Comment by gusennan** [comment]
Closing because not sure if it's still an issue.
