### ISSUE TITLE
Index out of bounds exception thrown in GradientDescentPFunc

### ISSUE THREAD

**Issue by gusennan** [donaldlab/OSPREY3#144]
This is frequently encountered (about 1/3 of runs) and looks to me to be caused by a score task being submitted when there are actually no scored confs. So the straightforward fix is not to submit a score task when there are no scores to submit.

Here's the exception:

```
edu.duke.cs.osprey.parallelism.TaskExecutor$TaskException: A task failed, no new tasks can be submitted
        at edu.duke.cs.osprey.parallelism.ConcurrentTaskExecutor.recordException(ConcurrentTaskExecutor.java:106)
        at edu.duke.cs.osprey.parallelism.ConcurrentTaskExecutor.taskSuccess(ConcurrentTaskExecutor.java:60)
        at edu.duke.cs.osprey.parallelism.ThreadPoolTaskExecutor.lambda$submit$0(ThreadPoolTaskExecutor.java:105)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
        at java.base/java.util.Objects.checkIndex(Objects.java:372)
        at java.base/java.util.ArrayList.get(ArrayList.java:459)
        at edu.duke.cs.osprey.kstar.pfunc.GradientDescentPfunc.onScores(GradientDescentPfunc.java:673)
        at edu.duke.cs.osprey.kstar.pfunc.GradientDescentPfunc.lambda$compute$1(GradientDescentPfunc.java:454)
        at edu.duke.cs.osprey.parallelism.ConcurrentTaskExecutor.taskSuccess(ConcurrentTaskExecutor.java:57)
```

**Comment by cuchaz** [comment]
Oh interesting... That score handler used to be able to handle empty lists, but looks like a recent change added extra tracking for statistics of some kind and broke the handler in a rare edge case. Ironically, those statistics don't appear to be used anywhere, so looks like the score handler is broken for no reason? lol.

Anyway, your fix seems fine to me. I'd run the unit tests for the pfunc code to guard against regressions. Just to be sure.

**Comment by gusennan** [comment]
Thanks and good idea. I ran all of the KStar tests.  10/93 failed, but looking at the stack traces it seems they're failing in the usable builder for the ecalc, not during the calculation of pfunc. A number of them timed out.

[Test Results - Tests_in_'edu_duke_cs_osprey_kstar'.zip](https://github.com/donaldlab/OSPREY3/files/5258090/Test.Results.-.Tests_in_.edu_duke_cs_osprey_kstar.zip)
