### ISSUE TITLE
I get a java exception when try ospray.start()

### ISSUE THREAD

**Issue by onlycparra** [donaldlab/OSPREY3#146]
Hi, this is my setup:
- Fresh installation of Ubuntu 20.04 updated.
- osprey 2.3.101 for linux python3
- Installed python3 and pip by `sudo apt install python3 python3-pip`
- Installed ospray by running the content of the `installer.sh` but replacing "python" with "python3" (I don't have python2). I finished without error.
```
$ python3 -m pip uninstall -y osprey
WARNING: Skipping osprey as it is not installed.
```

```
$ python3 -m pip install --user osprey --find-link=wheelhouse --pre
Looking in links: wheelhouse
Processing ./wheelhouse/osprey-3.2-py3-none-any.whl
Collecting JPype1>=0.7.2
  Downloading JPype1-1.0.2-cp38-cp38-manylinux2010_x86_64.whl (3.8 MB)
     |████████████████████████████████| 3.8 MB 7.6 MB/s 
Installing collected packages: JPype1, osprey
Successfully installed JPype1-1.0.2 osprey-3.2
```

I can import the module, but when I try to start it, I get a java exception:

```
>>> import osprey
>>> osprey.start()
Traceback (most recent call last):
  File "org.jpype.pkg.JPypePackageManager.java", line 58, in org.jpype.pkg.JPypePackageManager.<clinit>
  File "org.jpype.pkg.JPypePackageManager.java", line 139, in org.jpype.pkg.JPypePackageManager.getFileSystemProvider
java.nio.file.FileSystemNotFoundException: java.nio.file.FileSystemNotFoundException: Unable to find filesystem for jar

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "org.jpype.JPypeContext.java", line 519, in org.jpype.JPypeContext.getPackage
Exception: Java Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/username/.local/lib/python3.8/site-packages/osprey/__init__.py", line 191, in start
    wraps.init(c)
  File "/home/username/.local/lib/python3.8/site-packages/osprey/wraps.py", line 66, in init
    wrapStrandFlex(c)
  File "/home/username/.local/lib/python3.8/site-packages/osprey/wraps.py", line 111, in wrapStrandFlex
    jtype = jvm.getInnerClass(c.confspace.Strand, 'Flexibility')
java.lang.ExceptionInInitializerError: java.lang.ExceptionInInitializerError
```

Thanks in advance, and thanks for all the work done to come up with this software.

**Comment by cuchaz** [comment]
Hello, I think we've already fixed this issue ([see here](https://github.com/donaldlab/OSPREY3/issues/134)).

Try downloading the newest release [here](https://github.com/donaldlab/OSPREY3/releases/tag/3.2.203) and see if that solves the problem for you.

**Comment by gusennan** [comment]
Closing since no recent update.
