### ISSUE TITLE
Error when running prep.py

### ISSUE THREAD

**Issue by Patdi** [donaldlab/OSPREY3#185]
I'm running osprey on Ubuntu 20.04 with python3.8. when running the prep.py file on the example files in /examples/python.ccs/molecule prep and I've been getting the following error. Any help would be greatly appreciated.

WARNING: Using incubator modules: jdk.incubator.foreign
OSPREY 4.0.2.331, Python 3.8.10, Java 17.0.3, Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.29
Using up to 1024 MiB heap memory: 128 MiB for garbage, 896 MiB for storage
Loaded 2 molecules:
        Chain A: [Protein]
        EPE: [SmallMolecule]
14:10:58.718 [main] INFO  ktor.application - Autoreload is disabled because the development mode is off.
14:10:58.744 [main] INFO  ktor.application - Responding at http://0.0.0.0:44342
Osprey prep local service started
log4j:WARN No appenders could be found for logger (org.apache.http.impl.nio.client.MainClientExec).
log4j:WARN Please initialize the log4j system properly.
added 1277 bonds to Bovine PTPase
added 15 bonds to HEPES (EPE)
added 1237 hydrogens to Bovine PTPase
minimizing ...
Osprey prep local service stopped
Traceback (most recent call last):
  File "minimization.kt", line 67, in edu.duke.cs.osprey.gui.forcefield.amber.MinimizationKt.minimizeBlocking
  File "kotlinx.coroutines.BuildersKt.java", line 1, in kotlinx.coroutines.BuildersKt.runBlocking$default
  File "Builders.kt", line -1, in kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default
  File "kotlinx.coroutines.BuildersKt.java", line 1, in kotlinx.coroutines.BuildersKt.runBlocking
  File "Builders.kt", line 61, in kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking
  File "Builders.kt", line 86, in kotlinx.coroutines.BlockingCoroutine.joinBlocking
  File "EventLoop.common.kt", line 277, in kotlinx.coroutines.EventLoopImplBase.processNextEvent
  File "DispatchedTask.kt", line 106, in kotlinx.coroutines.DispatchedTask.run
  File "ContinuationImpl.kt", line 46, in kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith
  File "SuspendFunctionGun.kt", line 93, in io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith
  File "SuspendFunctionGun.kt", line 15, in io.ktor.util.pipeline.SuspendFunctionGun.access$loop
  File "SuspendFunctionGun.kt", line 147, in io.ktor.util.pipeline.SuspendFunctionGun.loop
  File "SuspendFunctionGun.kt", line 191, in io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith
  File "ContinuationImpl.kt", line 46, in kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith
  File "SuspendFunctionGun.kt", line 93, in io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith
  File "SuspendFunctionGun.kt", line 15, in io.ktor.util.pipeline.SuspendFunctionGun.access$loop
  File "SuspendFunctionGun.kt", line 147, in io.ktor.util.pipeline.SuspendFunctionGun.loop
  File "SuspendFunctionGun.kt", line 191, in io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith
  File "ContinuationImpl.kt", line 46, in kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith
  File "SuspendFunctionGun.kt", line 93, in io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith
  File "SuspendFunctionGun.kt", line 15, in io.ktor.util.pipeline.SuspendFunctionGun.access$loop
  File "SuspendFunctionGun.kt", line 147, in io.ktor.util.pipeline.SuspendFunctionGun.loop
  File "SuspendFunctionGun.kt", line 191, in io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith
  File "ContinuationImpl.kt", line 46, in kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith
  File "SuspendFunctionGun.kt", line 93, in io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith
  File "SuspendFunctionGun.kt", line 15, in io.ktor.util.pipeline.SuspendFunctionGun.access$loop
  File "SuspendFunctionGun.kt", line 147, in io.ktor.util.pipeline.SuspendFunctionGun.loop
  File "SuspendFunctionGun.kt", line 191, in io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith
  File "ContinuationImpl.kt", line 46, in kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith
  File "SuspendFunctionGun.kt", line 93, in io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith
  File "SuspendFunctionGun.kt", line 15, in io.ktor.util.pipeline.SuspendFunctionGun.access$loop
  File "SuspendFunctionGun.kt", line 147, in io.ktor.util.pipeline.SuspendFunctionGun.loop
  File "SuspendFunctionGun.kt", line 191, in io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith
  File "ContinuationImpl.kt", line 33, in kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith
  File "OspreyService.kt", line -1, in edu.duke.cs.osprey.gui.io.OspreyService$types$1.invokeSuspend
  File "OspreyService.kt", line 340, in edu.duke.cs.osprey.gui.io.OspreyService.types
  File "services.kt", line 25, in edu.duke.cs.osprey.service.ServiceResponse.responseOrThrow
Exception: Java Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "prep.py", line 106, in <module>
    osprey.prep.minimize(
  File "/home/usr/.local/lib/python3.8/site-packages/osprey/prep.py", line 434, in minimize
    osprey.c.gui.forcefield.amber.MinimizationKt.minimizeBlocking(jvm.toArrayList(minimizerInfos), numSteps)
edu.duke.cs.osprey.service.ServiceException: edu.duke.cs.osprey.service.ServiceException: Antechamber didn't produce an output molecule

Antechamber:

Welcome to antechamber 19.0: molecular input file processor.

Info: Total number of electrons: 128; net charge: 0

Running: /home/usr/.local/lib/python3.8/site-packages/osprey/progs/ambertools/bin/sqm -O -i sqm.in -o sqm.out
/home/usr/.local/lib/python3.8/site-packages/osprey/progs/ambertools/bin/sqm: error while loading shared libraries: libgfortran.so.4: cannot open shared object file: No such file or directory
/home/usr/.local/lib/python3.8/site-packages/osprey/progs/ambertools/bin/antechamber: Fatal Error!
Cannot properly run "/home/usr/.local/lib/python3.8/site-packages/osprey/progs/ambertools/bin/sqm -O -i sqm.in -o sqm.out".

**Comment by Patdi** [comment]
I was missing the ligfortran4 library. I installed it with:
sudo apt-get install libgfortran4

That resolved the issue.
