### ISSUE TITLE
issue running osprey from source

### ISSUE THREAD

**Issue by ONikeH** [donaldlab/OSPREY3#187]
Python 3.8.10 (default, Nov 14 2022, 12:59:47) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import osprey
>>> osprey.start()
WARNING: Using incubator modules: jdk.incubator.foreign
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vlad/Desktop/Test_Osprey_Che/Sucessful_Osprey_February/OSPREY3/src/main/python/osprey/__init__.py", line 249, in start
    _start_jvm_common(lambda jre_path: jvm.start(jre_path, heapSizeMiB, enableAssertions, stackSizeMiB, garbageSizeMiB, allowRemoteManagement, attachJvmDebugger))
  File "/home/vlad/Desktop/Test_Osprey_Che/Sucessful_Osprey_February/OSPREY3/src/main/python/osprey/__init__.py", line 179, in _start_jvm_common
    wraps.init(c)
  File "/home/vlad/Desktop/Test_Osprey_Che/Sucessful_Osprey_February/OSPREY3/src/main/python/osprey/wraps.py", line 66, in init
    wrapStrandFlex(c)
  File "/home/vlad/Desktop/Test_Osprey_Che/Sucessful_Osprey_February/OSPREY3/src/main/python/osprey/wraps.py", line 111, in wrapStrandFlex
    jtype = jvm.getInnerClass(c.confspace.Strand, 'Flexibility')
AttributeError: Java package 'edu.duke.cs.osprey' has no attribute 'confspace'

**Comment by ONikeH** [comment]
Fixed: i did not run ./gradlew assemble

Closed
