### ISSUE TITLE
GLIBC Importerror

### ISSUE THREAD

**Issue by castephens** [donaldlab/OSPREY3#96]
Hi, I tried installing and importing opsrey and received the following error message:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/netapp/home/castephens/.local/lib/python2.7/site-packages/osprey/__init__.py", line 2, in <module>
    import sys, os, jpype
  File "/netapp/home/castephens/.local/lib/python2.7/site-packages/jpype/__init__.py", line 17, in <module>
    from _jpackage import *
  File "/netapp/home/castephens/.local/lib/python2.7/site-packages/jpype/_jpackage.py", line 18, in <module>
    import _jpype
ImportError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /netapp/home/castephens/.local/lib/python2.7/site-packages/_jpype.so)

I think this means that you complied on a different version of the library? Do you have any instructions for installing this from the source? 

System details:
OS: CentOS 7
python: 2.7.5
java: 1.8.0_201

thanks!

**Comment by cuchaz** [comment]
Hi there,

> I think this means that you complied on a different version of the library?

Yeah, that sounds right.

> Do you have any instructions for installing this from the source?

The source for that library should be [here](https://github.com/donaldlab/jpype-py2). To compile it, just run
```
python setup.py bdist_wheel
```

Then install the resulting python wheel over the existing `jpype-py2` package (the one that osprey installed) using `pip`.

**Comment by gusennan** [comment]
Closing for lack of activity.
