### ISSUE TITLE
Osprey crashes when calculating GMEC of butane

### ISSUE THREAD

**Issue by gusennan** [donaldlab/OSPREY3#99]
Please find attached a minimalistic GMEC script to calculate the energy of butane. Please also find attached the molecule butane in pdb format.
This script does not load a proper protein-ligand complex (I can send that to you, as well, if needed). However, the error message is the same.

[GMECbutane.py.txt](https://github.com/donaldlab/OSPREY3/files/3271979/GMECbutane.py.txt)
[butane.pdb.txt](https://github.com/donaldlab/OSPREY3/files/3271980/butane.pdb.txt)

P.S.: Version numbers and error message:

```
OSPREY version: OSPREY 3.0-beta1 (https://github.com/donaldlab/OSPREY3/releases/download/v3.0b1/osprey-python-3.0-beta1.zip)
OS (uname -a): Linux CARNIFEX 4.4.0-125-generic #150-Ubuntu SMP Thu May 10 07:14:00 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
Ubuntu: Ubuntu 16.04.4 LTS
Python: Python 2.7.12
Error message:
andreas@CARNIFEX:~/osprey-test$ python2 GMECbutane.py 
OSPREY 3.0-beta1
read PDB file from file: butane.pdb
Calculating energy matrix with 1 entries...
Traceback (most recent call last):
  File "GMECbutane.py", line 88, in <module>
    emat = osprey.EnergyMatrix(confEcalc)
  File "/CLUSTERFS/homes/andreas/.local/lib/python2.7/site-packages/osprey/__init__.py", line 503, in EnergyMatrix
    return builder.build().calcEnergyMatrix()
jpype._jexception.NullPointerExceptionPyRaisable: java.lang.NullPointerException

java.lang.NullPointerException
at edu.duke.cs.osprey.dof.MutAlignment.<init>(MutAlignment.java:44)
at edu.duke.cs.osprey.dof.ResidueTypeDOF.switchToTemplate(ResidueTypeDOF.java:102)
at edu.duke.cs.osprey.confspace.SimpleConfSpace$ResidueConf.updateResidue(SimpleConfSpace.java:174)
at edu.duke.cs.osprey.confspace.SimpleConfSpace.makeMolecule(SimpleConfSpace.java:501)
at edu.duke.cs.osprey.energy.ConfEnergyCalculator.calcEnergy(ConfEnergyCalculator.java:133)
at edu.duke.cs.osprey.energy.ConfEnergyCalculator.calcSingleEnergy(ConfEnergyCalculator.java:104)
at edu.duke.cs.osprey.ematrix.SimplerEnergyMatrixCalculator$1Batch.lambda$submitTask$0(SimplerEnergyMatrixCalculator.java:123)
at edu.duke.cs.osprey.parallelism.TaskExecutor.submit(TaskExecutor.java:28)
at edu.duke.cs.osprey.ematrix.SimplerEnergyMatrixCalculator$1Batch.submitTask(SimplerEnergyMatrixCalculator.java:116)
at edu.duke.cs.osprey.ematrix.SimplerEnergyMatrixCalculator$1Batcher.submit(SimplerEnergyMatrixCalculator.java:170)
at edu.duke.cs.osprey.ematrix.SimplerEnergyMatrixCalculator.reallyCalcEnergyMatrix(SimplerEnergyMatrixCalculator.java:196)
at edu.duke.cs.osprey.ematrix.SimplerEnergyMatrixCalculator.calcEnergyMatrix(SimplerEnergyMatrixCalculator.java:83)
```

**Comment by archie18** [comment]
This is my error report. Please kindly let me know, whether you need anymore information.

**Comment by gusennan** [comment]
Closing due to inactivity.
